// Auto-generated — do not edit by hand.
// TM disc sprites: one per type (PokeAPI, CC0)
export const TM_DISC: Record<string, number> = {
  normal:   require('../assets/items/tms/tm-normal.png'),
  fire:     require('../assets/items/tms/tm-fire.png'),
  water:    require('../assets/items/tms/tm-water.png'),
  electric: require('../assets/items/tms/tm-electric.png'),
  grass:    require('../assets/items/tms/tm-grass.png'),
  ice:      require('../assets/items/tms/tm-ice.png'),
  fighting: require('../assets/items/tms/tm-fighting.png'),
  poison:   require('../assets/items/tms/tm-poison.png'),
  ground:   require('../assets/items/tms/tm-ground.png'),
  flying:   require('../assets/items/tms/tm-flying.png'),
  psychic:  require('../assets/items/tms/tm-psychic.png'),
  bug:      require('../assets/items/tms/tm-bug.png'),
  rock:     require('../assets/items/tms/tm-rock.png'),
  ghost:    require('../assets/items/tms/tm-ghost.png'),
  dragon:   require('../assets/items/tms/tm-dragon.png'),
  dark:     require('../assets/items/tms/tm-dark.png'),
  steel:    require('../assets/items/tms/tm-steel.png'),
  fairy:    require('../assets/items/tms/tm-fairy.png'),
};

// Mega Stone item sprites — official ones only (PokeAPI, CC0).
// Hack-specific stones without an official sprite are absent; fall back to Pokémon sprite.
export const MEGA_STONE: Record<string, number> = {
  'venusaurite':    require('../assets/items/megastones/venusaurite.png'),
  'charizardite-x': require('../assets/items/megastones/charizardite-x.png'),
  'blastoisinite':  require('../assets/items/megastones/blastoisinite.png'),
  'sceptilite':     require('../assets/items/megastones/sceptilite.png'),
  'blazikenite':    require('../assets/items/megastones/blazikenite.png'),
  'swampertite':    require('../assets/items/megastones/swampertite.png'),
  'lucarionite':    require('../assets/items/megastones/lucarionite.png'),
  'alakazite':      require('../assets/items/megastones/alakazite.png'),
  'sablenite':      require('../assets/items/megastones/sablenite.png'),
  'kangaskhanite':  require('../assets/items/megastones/kangaskhanite.png'),
  'audinite':       require('../assets/items/megastones/audinite.png'),
  'gardevoirite':   require('../assets/items/megastones/gardevoirite.png'),
  'absolite':       require('../assets/items/megastones/absolite.png'),
  'altarianite':    require('../assets/items/megastones/altarianite.png'),
  'sharpedonite':   require('../assets/items/megastones/sharpedonite.png'),
  'heracronite':    require('../assets/items/megastones/heracronite.png'),
  'lopunnite':      require('../assets/items/megastones/lopunnite.png'),
  'pidgeotite':     require('../assets/items/megastones/pidgeotite.png'),
  'glalitite':      require('../assets/items/megastones/glalitite.png'),
  'abomasite':      require('../assets/items/megastones/abomasite.png'),
  'medichamite':    require('../assets/items/megastones/medichamite.png'),
  'latiosite':      require('../assets/items/megastones/latiosite.png'),
  'latiasite':      require('../assets/items/megastones/latiasite.png'),
  'aggronite':      require('../assets/items/megastones/aggronite.png'),
  'steelixite':     require('../assets/items/megastones/steelixite.png'),
  'cameruptite':    require('../assets/items/megastones/cameruptite.png'),
  'charizardite-y': require('../assets/items/megastones/charizardite-y.png'),
  'tyranitarite':   require('../assets/items/megastones/tyranitarite.png'),
  'mawilite':       require('../assets/items/megastones/mawilite.png'),
  'houndoominite':  require('../assets/items/megastones/houndoominite.png'),
  'mewtwonite-y':   require('../assets/items/megastones/mewtwonite-y.png'),
  'pinsirite':      require('../assets/items/megastones/pinsirite.png'),
  'ampharosite':    require('../assets/items/megastones/ampharosite.png'),
  'slowbronite':    require('../assets/items/megastones/slowbronite.png'),
  'salamencite':    require('../assets/items/megastones/salamencite.png'),
  'scizorite':      require('../assets/items/megastones/scizorite.png'),
  'garchompite':    require('../assets/items/megastones/garchompite.png'),
  'metagrossite':   require('../assets/items/megastones/metagrossite.png'),
  'aerodactylite':  require('../assets/items/megastones/aerodactylite.png'),
  'gyaradosite':    require('../assets/items/megastones/gyaradosite.png'),
  'manectite':      require('../assets/items/megastones/manectite.png'),
  'galladite':      require('../assets/items/megastones/galladite.png'),
  'gengarite':      require('../assets/items/megastones/gengarite.png'),
  'banettite':      require('../assets/items/megastones/banettite.png'),
  'diancite':       require('../assets/items/megastones/diancite.png'),
  'mewtwonite-x':   require('../assets/items/megastones/mewtwonite-x.png'),
};
