// Held-item sprites (PokeAPI, CC0). Key = lowercase hyphenated item name.
export const HELD_ITEM: Record<string, number> = {
  'air-balloon':    require('../assets/items/held/air-balloon.png'),
  'assault-vest':   require('../assets/items/held/assault-vest.png'),
  'berry-juice':    require('../assets/items/held/berry-juice.png'),
  'big-root':       require('../assets/items/held/big-root.png'),
  'black-glasses':  require('../assets/items/held/black-glasses.png'),
  'black-sludge':   require('../assets/items/held/black-sludge.png'),
  'charcoal':       require('../assets/items/held/charcoal.png'),
  'charti-berry':   require('../assets/items/held/charti-berry.png'),
  'chesto-berry':   require('../assets/items/held/chesto-berry.png'),
  'choice-band':    require('../assets/items/held/choice-band.png'),
  'choice-scarf':   require('../assets/items/held/choice-scarf.png'),
  'choice-specs':   require('../assets/items/held/choice-specs.png'),
  'chople-berry':   require('../assets/items/held/chople-berry.png'),
  'coba-berry':     require('../assets/items/held/coba-berry.png'),
  'colbur-berry':   require('../assets/items/held/colbur-berry.png'),
  'custap-berry':   require('../assets/items/held/custap-berry.png'),
  'damp-rock':      require('../assets/items/held/damp-rock.png'),
  'dark-gem':       require('../assets/items/held/dark-gem.png'),
  'deep-sea-tooth': require('../assets/items/held/deep-sea-tooth.png'),
  'draco-plate':    require('../assets/items/held/draco-plate.png'),
  'dragon-fang':    require('../assets/items/held/dragon-fang.png'),
  'electric-seed':  require('../assets/items/held/electric-seed.png'),
  'expert-belt':    require('../assets/items/held/expert-belt.png'),
  'fighting-gem':   require('../assets/items/held/fighting-gem.png'),
  'figy-berry':     require('../assets/items/held/figy-berry.png'),
  'focus-sash':     require('../assets/items/held/focus-sash.png'),
  'grassy-seed':    require('../assets/items/held/grassy-seed.png'),
  'hard-stone':     require('../assets/items/held/hard-stone.png'),
  'heat-rock':      require('../assets/items/held/heat-rock.png'),
  'iapapa-berry':   require('../assets/items/held/iapapa-berry.png'),
  'icy-rock':       require('../assets/items/held/icy-rock.png'),
  'kings-rock':     require('../assets/items/held/kings-rock.png'),
  'leftovers':      require('../assets/items/held/leftovers.png'),
  'life-orb':       require('../assets/items/held/life-orb.png'),
  'light-ball':     require('../assets/items/held/light-ball.png'),
  'light-clay':     require('../assets/items/held/light-clay.png'),
  'lum-berry':      require('../assets/items/held/lum-berry.png'),
  'magnet':         require('../assets/items/held/magnet.png'),
  'metal-coat':     require('../assets/items/held/metal-coat.png'),
  'metronome':      require('../assets/items/held/metronome.png'),
  'miracle-seed':   require('../assets/items/held/miracle-seed.png'),
  'misty-seed':     require('../assets/items/held/misty-seed.png'),
  'muscle-band':    require('../assets/items/held/muscle-band.png'),
  'mystic-water':   require('../assets/items/held/mystic-water.png'),
  'never-melt-ice': require('../assets/items/held/never-melt-ice.png'),
  'normal-gem':     require('../assets/items/held/normal-gem.png'),
  'occa-berry':     require('../assets/items/held/occa-berry.png'),
  'oran-berry':     require('../assets/items/held/oran-berry.png'),
  'passho-berry':   require('../assets/items/held/passho-berry.png'),
  'pixie-plate':    require('../assets/items/held/pixie-plate.png'),
  'poison-barb':    require('../assets/items/held/poison-barb.png'),
  'power-herb':     require('../assets/items/held/power-herb.png'),
  'psychic-seed':   require('../assets/items/held/psychic-seed.png'),
  'quick-claw':     require('../assets/items/held/quick-claw.png'),
  'reaper-cloth':   require('../assets/items/held/reaper-cloth.png'),
  'rindo-berry':    require('../assets/items/held/rindo-berry.png'),
  'rocky-helmet':   require('../assets/items/held/rocky-helmet.png'),
  'safety-goggles': require('../assets/items/held/safety-goggles.png'),
  'salac-berry':    require('../assets/items/held/salac-berry.png'),
  'scope-lens':     require('../assets/items/held/scope-lens.png'),
  'sharp-beak':     require('../assets/items/held/sharp-beak.png'),
  'shell-bell':     require('../assets/items/held/shell-bell.png'),
  'shuca-berry':    require('../assets/items/held/shuca-berry.png'),
  'silk-scarf':     require('../assets/items/held/silk-scarf.png'),
  'silver-powder':  require('../assets/items/held/silver-powder.png'),
  'sitrus-berry':   require('../assets/items/held/sitrus-berry.png'),
  'smooth-rock':    require('../assets/items/held/smooth-rock.png'),
  'soft-sand':      require('../assets/items/held/soft-sand.png'),
  'spell-tag':      require('../assets/items/held/spell-tag.png'),
  'terrain-extender': require('../assets/items/held/terrain-extender.png'),
  'thick-club':     require('../assets/items/held/thick-club.png'),
  'twisted-spoon':  require('../assets/items/held/twisted-spoon.png'),
  'wacan-berry':    require('../assets/items/held/wacan-berry.png'),
  'weakness-policy': require('../assets/items/held/weakness-policy.png'),
  'white-herb':     require('../assets/items/held/white-herb.png'),
  'wide-lens':      require('../assets/items/held/wide-lens.png'),
  'wise-glasses':   require('../assets/items/held/wise-glasses.png'),
  'yache-berry':    require('../assets/items/held/yache-berry.png'),
};

export function resolveHeldItem(name: string | null | undefined): number | null {
  if (!name) return null;
  const slug = name.toLowerCase().replace(/[''']/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return HELD_ITEM[slug] ?? null;
}

// Auto-generated — do not edit by hand.
// TM disc sprites: one per type (PokeAPI, CC0)
export const TM_DISC: Record<string, number> = {
  normal:   require('../assets/items/tms/tm-normal.png'),
  fire:     require('../assets/items/tms/tm-fire.png'),
  water:    require('../assets/items/tms/tm-water.png'),
  electric: require('../assets/items/tms/tm-electric.png'),
  grass:    require('../assets/items/tms/tm-grass.png'),
  ice:      require('../assets/items/tms/tm-ice.png'),
  fighting: require('../assets/items/tms/tm-fighting.png'),
  poison:   require('../assets/items/tms/tm-poison.png'),
  ground:   require('../assets/items/tms/tm-ground.png'),
  flying:   require('../assets/items/tms/tm-flying.png'),
  psychic:  require('../assets/items/tms/tm-psychic.png'),
  bug:      require('../assets/items/tms/tm-bug.png'),
  rock:     require('../assets/items/tms/tm-rock.png'),
  ghost:    require('../assets/items/tms/tm-ghost.png'),
  dragon:   require('../assets/items/tms/tm-dragon.png'),
  dark:     require('../assets/items/tms/tm-dark.png'),
  steel:    require('../assets/items/tms/tm-steel.png'),
  fairy:    require('../assets/items/tms/tm-fairy.png'),
};

// Mega Stone item sprites — official ones only (PokeAPI, CC0).
// Hack-specific stones without an official sprite are absent; fall back to Pokémon sprite.
export const MEGA_STONE: Record<string, number> = {
  'venusaurite':    require('../assets/items/megastones/venusaurite.png'),
  'charizardite-x': require('../assets/items/megastones/charizardite-x.png'),
  'blastoisinite':  require('../assets/items/megastones/blastoisinite.png'),
  'sceptilite':     require('../assets/items/megastones/sceptilite.png'),
  'blazikenite':    require('../assets/items/megastones/blazikenite.png'),
  'swampertite':    require('../assets/items/megastones/swampertite.png'),
  'lucarionite':    require('../assets/items/megastones/lucarionite.png'),
  'alakazite':      require('../assets/items/megastones/alakazite.png'),
  'sablenite':      require('../assets/items/megastones/sablenite.png'),
  'kangaskhanite':  require('../assets/items/megastones/kangaskhanite.png'),
  'audinite':       require('../assets/items/megastones/audinite.png'),
  'gardevoirite':   require('../assets/items/megastones/gardevoirite.png'),
  'absolite':       require('../assets/items/megastones/absolite.png'),
  'altarianite':    require('../assets/items/megastones/altarianite.png'),
  'sharpedonite':   require('../assets/items/megastones/sharpedonite.png'),
  'heracronite':    require('../assets/items/megastones/heracronite.png'),
  'lopunnite':      require('../assets/items/megastones/lopunnite.png'),
  'pidgeotite':     require('../assets/items/megastones/pidgeotite.png'),
  'glalitite':      require('../assets/items/megastones/glalitite.png'),
  'abomasite':      require('../assets/items/megastones/abomasite.png'),
  'medichamite':    require('../assets/items/megastones/medichamite.png'),
  'latiosite':      require('../assets/items/megastones/latiosite.png'),
  'latiasite':      require('../assets/items/megastones/latiasite.png'),
  'aggronite':      require('../assets/items/megastones/aggronite.png'),
  'steelixite':     require('../assets/items/megastones/steelixite.png'),
  'cameruptite':    require('../assets/items/megastones/cameruptite.png'),
  'charizardite-y': require('../assets/items/megastones/charizardite-y.png'),
  'tyranitarite':   require('../assets/items/megastones/tyranitarite.png'),
  'mawilite':       require('../assets/items/megastones/mawilite.png'),
  'houndoominite':  require('../assets/items/megastones/houndoominite.png'),
  'mewtwonite-y':   require('../assets/items/megastones/mewtwonite-y.png'),
  'pinsirite':      require('../assets/items/megastones/pinsirite.png'),
  'ampharosite':    require('../assets/items/megastones/ampharosite.png'),
  'slowbronite':    require('../assets/items/megastones/slowbronite.png'),
  'salamencite':    require('../assets/items/megastones/salamencite.png'),
  'scizorite':      require('../assets/items/megastones/scizorite.png'),
  'garchompite':    require('../assets/items/megastones/garchompite.png'),
  'metagrossite':   require('../assets/items/megastones/metagrossite.png'),
  'aerodactylite':  require('../assets/items/megastones/aerodactylite.png'),
  'gyaradosite':    require('../assets/items/megastones/gyaradosite.png'),
  'manectite':      require('../assets/items/megastones/manectite.png'),
  'galladite':      require('../assets/items/megastones/galladite.png'),
  'galladeite':     require('../assets/items/megastones/galladite.png'),  // alternate RR spelling
  'gengarite':      require('../assets/items/megastones/gengarite.png'),
  'banettite':      require('../assets/items/megastones/banettite.png'),
  'diancite':       require('../assets/items/megastones/diancite.png'),
  'mewtwonite-x':   require('../assets/items/megastones/mewtwonite-x.png'),
};
