// Trainer sprite lookup — exact name first, then trainer-class prefix.
// Keys are lowercase. Prefix keys must come AFTER longer exact keys.

export const TRAINER_SPRITE: Record<string, number> = {
  // ── Radical Red — exact name matches (sprites extracted from xlsx) ────────
  'ace trainer derek (gym mini bosses) (starting sunlight)': require('../assets/trainers/rr-ace-trainer-cinnabar.png'),
  'ace trainer lucy (starting sunlight)':  require('../assets/trainers/rr-ace-trainer-cinnabar.png'),
  'ace trainer zac (double battle) (starting sunlight)': require('../assets/trainers/rr-ace-trainer-cinnabar.png'),
  'ace trainer alexa':                     require('../assets/trainers/rr-ace-trainer-haley.png'),
  'ace trainer caroline':                  require('../assets/trainers/rr-ace-trainer-haley.png'),
  'ace trainer colby':                     require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'ace trainer cole (route 8)':            require('../assets/trainers/rr-ace-trainer-cole-route-8.png'),
  'ace trainer george':                    require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'ace trainer haley':                     require('../assets/trainers/rr-ace-trainer-haley.png'),
  'ace trainer mary':                      require('../assets/trainers/rr-ace-trainer-nelle.png'),
  'ace trainer naomi':                     require('../assets/trainers/rr-ace-trainer-haley.png'),
  'ace trainer nelle':                     require('../assets/trainers/rr-ace-trainer-nelle.png'),
  'ace trainer rolando':                   require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'ace trainer wilton':                    require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'agatha team 1':                         require('../assets/trainers/rr-agatha-team-1.png'),
  'agatha team 2':                         require('../assets/trainers/rr-agatha-team-1.png'),
  'archer':                                require('../assets/trainers/rr-rocket-admin-archer.png'),
  'ariana & archer (silph co.) tag team battle': require('../assets/trainers/rr-ariana-archer.png'),
  'ariana':                                require('../assets/trainers/rr-ariana.png'),
  'biker hideo':                           require('../assets/trainers/rr-biker-jared.png'),
  'biker jared':                           require('../assets/trainers/rr-biker-jared.png'),
  'biker koji':                            require('../assets/trainers/rr-biker-jared.png'),
  'biker lao':                             require('../assets/trainers/rr-biker-jared.png'),
  'biker luke':                            require('../assets/trainers/rr-biker-jared.png'),
  'biker ruben':                           require('../assets/trainers/rr-biker-jared.png'),
  'biker william':                         require('../assets/trainers/rr-biker-jared.png'),
  'beauty lola and beauty sheila (tag battle) (double battle) (unskippable)': require('../assets/trainers/rr-beauties.png'),
  'bird keeper jacob':                     require('../assets/trainers/rr-bird-keeper-jacob.png'),
  'bird keeper jason':                     require('../assets/trainers/rr-bird-keeper-jason.png'),
  'bird keeper perry':                     require('../assets/trainers/rr-bird-keeper-sebastian.png'),
  'bird keeper robert (can be skipped after biker jared moves towards you)': require('../assets/trainers/rr-bird-keeper-sebastian.png'),
  'bird keeper sebastian':                 require('../assets/trainers/rr-bird-keeper-sebastian.png'),
  'brendan':                               require('../assets/trainers/rr-brendan.png'),
  'brendan (s.s. anne)':                   require('../assets/trainers/rr-brendan-ss-anne.png'),
  'blaine':                                require('../assets/trainers/rr-blaine.gif'),
  'brock-kun':                             require('../assets/trainers/rr-brock-kun.gif'),
  'bruno team 1':                          require('../assets/trainers/rr-bruno-team-1.png'),
  'bruno team 2':                          require('../assets/trainers/rr-bruno-team-1.png'),
  'bug catcher cale':                      require('../assets/trainers/rr-bug-catcher-cale.png'),
  'bugsy (post-surge)':                    require('../assets/trainers/rr-bugsy.gif'),
  'bugsy (pre-surge)':                     require('../assets/trainers/rr-bugsy.gif'),
  'burglar max':                           require('../assets/trainers/rr-burglar-max.png'),
  'burglar anson':                         require('../assets/trainers/rr-burglar-max.png'),
  'camper ethan (nugget bridge)':          require('../assets/trainers/rr-camper-ethan-nugget-bridge.png'),
  'camper justin (route 12) (b2b)':        require('../assets/trainers/rr-camper-justin-route-12-b2b.png'),
  'celadon city game corner giovanni':     require('../assets/trainers/rr-celadon-city-game-corner-giovanni.gif'),
  'cerulean cave giovanni (double battle)': require('../assets/trainers/rr-celadon-city-game-corner-giovanni.gif'),
  'champion (if you chose bulbasaur)':     require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'champion (if you chose charmander)':    require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'champion (if you chose squirtle)':      require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'chuck (dojo) (drian punch tm)':         require('../assets/trainers/rr-chuck-dojo-drian-punch-tm.gif'),
  'clair':                                 require('../assets/trainers/rr-clair.gif'),
  'cue ball camron':                       require('../assets/trainers/rr-cue-ball-camron.png'),
  'dragon tamer ramiro':                   require('../assets/trainers/rr-dragon-tamer-ramiro.png'),
  'dumbass jojo fan (power plant)':        require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'dumbass kid (saffron city)':            require('../assets/trainers/rr-dumbass-kid-saffron-city.png'),
  'erika':                                 require('../assets/trainers/rr-erika.gif'),
  'falkner':                               require('../assets/trainers/rr-falkner.gif'),
  'fisherman andrew (route 12) (b2b)':     require('../assets/trainers/rr-fisherman-andrew-route-12-b2b.png'),
  'if you chose a fire starter':           require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'if you chose a grass starter':          require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'if you chose a water starter':          require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'if you chose bulbasaur':                require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'if you chose charmander':               require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'if you chose squirtle':                 require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'lance (partner)':                       require('../assets/trainers/rr-lance.gif'),
  'lance team 1':                          require('../assets/trainers/rr-lance.gif'),
  'lance team 2':                          require('../assets/trainers/rr-lance.gif'),
  'lass ali':                              require('../assets/trainers/rr-lass-anne.png'),
  'lass ann & gentleman brooks':           require('../assets/trainers/rr-brooks-ann.png'),
  'lass anne':                             require('../assets/trainers/rr-lass-anne.png'),
  'lass reli':                             require('../assets/trainers/rr-lass-anne.png'),
  'lorelei hail (double battle)':          require('../assets/trainers/rr-lorelei-rain-double-battle.png'),
  'lorelei rain (double battle)':          require('../assets/trainers/rr-lorelei-rain-double-battle.png'),
  'ghost omni-boost':                      require('../assets/trainers/rr-ghost-omni-boost.gif'),
  'gym leader blaine (starting sunlight)': require('../assets/trainers/rr-blaine.gif'),
  'jasmine 1':                             require('../assets/trainers/rr-jasmine.gif'),
  'jasmine 2':                             require('../assets/trainers/rr-jasmine.gif'),
  'jasmine 3':                             require('../assets/trainers/rr-jasmine.gif'),
  'koga':                                  require('../assets/trainers/rr-koga.gif'),
  'lt. surge':                             require('../assets/trainers/rr-lt-surge.gif'),
  'may':                                   require('../assets/trainers/rr-may.png'),
  'misty':                                 require('../assets/trainers/rr-misty.gif'),
  'morty':                                 require('../assets/trainers/rr-morty.gif'),
  'nugget bridge grunt':                   require('../assets/trainers/rr-nugget-bridge-grunt.png'),
  'picnicker alma':                        require('../assets/trainers/rr-picnicker-susie.png'),
  'picnicker caitlin (route 9)':           require('../assets/trainers/rr-picnicker-caitlin-route-9.png'),
  'picnicker susie':                       require('../assets/trainers/rr-picnicker-susie.png'),
  'pokemon trainer ketchup part 1':        require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'pokemon trainer ketchup part 2':        require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'pryce':                                 require('../assets/trainers/rr-pryce.gif'),
  'rival (silph co) if you chose a fire starter':   require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'rival (silph co) if you chose a water starter':  require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'rival (silph co.) if you chose a grass starter': require('../assets/trainers/rr-if-you-chose-a-fire-starter.gif'),
  'rocker luca (route 12)':                require('../assets/trainers/rr-rocker-luca-route-12.png'),
  'rocket admin archer':                   require('../assets/trainers/rr-rocket-admin-archer.png'),
  'silph co. giovanni':                    require('../assets/trainers/rr-celadon-city-game-corner-giovanni.gif'),
  'rocket grunt':                          require('../assets/trainers/rr-nugget-bridge-grunt.png'),
  'rocket grunt guard (left)':             require('../assets/trainers/rr-nugget-bridge-grunt.png'),
  'rocket grunt guard (right)':            require('../assets/trainers/rr-nugget-bridge-grunt.png'),
  'route 23 rising badge gate':            require('../assets/trainers/rr-brendan.png'),
  'sabrina (double battle)':               require('../assets/trainers/rr-sabrina-double-battle.gif'),
  'sam first fight':                       require('../assets/trainers/rr-sam-first-fight.png'),
  'shelly second fight':                   require('../assets/trainers/rr-sam-first-fight.png'),
  'super nerd miguel':                     require('../assets/trainers/rr-super-nerd-miguel.png'),
  'team rocket grunt (dig house)':         require('../assets/trainers/rr-nugget-bridge-grunt.png'),
  'trevor & edmond':                       require('../assets/trainers/rr-trevor-edmond.png'),
  'cool couple ray and tyra (double)':     require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'whitney':                               require('../assets/trainers/rr-whitney.gif'),
  'youngster timmy':                       require('../assets/trainers/rr-youngster-timmy.png'),

  // ── Radical Red — class prefix fallbacks (matched by startsWith) ─────────
  'ace trainer':  require('../assets/trainers/rr-ace-trainer-wilton.png'),
  'biker':        require('../assets/trainers/rr-biker-jared.png'),
  'bird keeper':  require('../assets/trainers/rr-bird-keeper-sebastian.png'),
  'bug catcher':  require('../assets/trainers/rr-bug-catcher-cale.png'),
  'camper':       require('../assets/trainers/rr-camper-ethan-nugget-bridge.png'),
  'cue ball':     require('../assets/trainers/rr-cue-ball-camron.png'),
  'dragon tamer': require('../assets/trainers/rr-bird-keeper-jacob.png'),
  'fisherman':    require('../assets/trainers/rr-fisherman-andrew-route-12-b2b.png'),
  'lass':         require('../assets/trainers/rr-lass-anne.png'),
  'picnicker':    require('../assets/trainers/rr-picnicker-susie.png'),
  'rocket admin': require('../assets/trainers/rr-rocket-admin-archer.png'),
  'rocker':       require('../assets/trainers/rr-rocker-luca-route-12.png'),
  'super nerd':   require('../assets/trainers/rr-super-nerd-miguel.png'),
  'youngster':    require('../assets/trainers/rr-youngster-timmy.png'),

  // ── Emerald Imperium — Gym Leaders & Elite Four ───────────────────────────
  'roxanne':                                                          require('../assets/trainers/ei-image31.png'),
  'roxanne - rustboro city':                                          require('../assets/trainers/ei-image31.png'),
  'brawly - dewford town':                                            require('../assets/trainers/ei-image6.png'),
  'wattson':                                                          require('../assets/trainers/ei-image67.png'),
  'wattson - mauville city':                                          require('../assets/trainers/ei-image67.png'),
  'flannery':                                                         require('../assets/trainers/ei-image44.png'),
  'norman':                                                           require('../assets/trainers/ei-image53.png'),
  'norman - petalburg city':                                          require('../assets/trainers/ei-image53.png'),
  'winona':                                                           require('../assets/trainers/ei-image15.png'),
  'winona - fortree city':                                            require('../assets/trainers/ei-image15.png'),
  'tate & liza (double battle)':                                      require('../assets/trainers/ei-image35.png'),
  'tate & liza (double battle) - mossdeep city':                     require('../assets/trainers/ei-image35.png'),
  'juan - sootopolis city':                                           require('../assets/trainers/ei-image42.png'),
  'candice - route 116':                                              require('../assets/trainers/ei-image287.png'),
  'gardenia - petalburg woods (pre-3rd gym badge)':                   require('../assets/trainers/ei-image122.png'),
  'gardenia - petalburg woods (post 3rd gym badge)':                  require('../assets/trainers/ei-image122.png'),
  'gardenia - petalburg woods (post 3rd gym badge) (optional)':       require('../assets/trainers/ei-image122.png'),
  'fantina - route 117':                                              require('../assets/trainers/ei-image93.png'),
  'fantina - route 117 (optional)':                                   require('../assets/trainers/ei-image93.png'),
  'maylene - jagged pass':                                            require('../assets/trainers/ei-image110.png'),
  'maylene - jagged pass (optional)':                                 require('../assets/trainers/ei-image110.png'),
  'crasher wake - route 118 (surf required)':                         require('../assets/trainers/ei-image115.png'),
  'crasher wake - route 118 (optional) (surf required)':              require('../assets/trainers/ei-image115.png'),
  'byron - route 121 (permanent rain)':                               require('../assets/trainers/ei-image124.png'),
  'byron - route 121 (permanent rain) (optional)':                    require('../assets/trainers/ei-image124.png'),
  'roark - outside shoal cave':                                       require('../assets/trainers/ei-image128.png'),
  'volkner - evergrande city (optional)':                             require('../assets/trainers/ei-image150.png'),
  'elite four - sidney (team 1) aka sydney tailwind':                 require('../assets/trainers/ei-image708.png'),
  'elite four - sidney (team 2) aka sydney trickroom':                require('../assets/trainers/ei-image708.png'),
  'elite four - phoebe (team 1) aka phoebe dusknoir':                 require('../assets/trainers/ei-image348.png'),
  'elite four - phoebe (team 2) aka phoebe gengar':                   require('../assets/trainers/ei-image348.png'),
  'elite four - glacia (team 1) aka glacia sun':                      require('../assets/trainers/ei-image732.png'),
  'elite four - glacia (team 2) aka glacia snow':                     require('../assets/trainers/ei-image732.png'),
  'elite four drake - sky pillar (true double battle)':               require('../assets/trainers/ei-image604.png'),
  'elite four - cynthia':                                             require('../assets/trainers/ei-image750.png'),
  'champion wallace & steven (double battle)':                        require('../assets/trainers/ei-image747.png'),

  // ── Emerald Imperium — Rivals ─────────────────────────────────────────────
  'rival fight (brendan / may) - route 103 (chooses type that beats your starter)': require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - rustboro city (if you chose grass starter)':       require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - rustboro city (if you chose fire starter)':        require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - route 110 (if you chose water starter)':           require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 110 (if you chose grass starter)':           require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 110 (if you chose fire starter)':            require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - rustboro city (if you chose water starter)':        require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 119 (if you chose water starter)':           require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 119 (if you chose grass starter)':           require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - route 119 (if you chose fire starter)':            require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - evergrande city (if you chose water starter)':     require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - evergrande city (if you chose grass starter)':     require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - evergrande city (if you chose fire starter)':      require('../assets/trainers/ei-image134.png'),
  'dawn - route 104':        require('../assets/trainers/ei-image149.png'),
  'dawn - route 111':        require('../assets/trainers/ei-image149.png'),
  'dawn - lilycove city':    require('../assets/trainers/ei-image149.png'),
  'dawn - evergrande city':  require('../assets/trainers/ei-image149.png'),
  'wally - mauville city':   require('../assets/trainers/ei-image284.png'),
  'wally - route 110':       require('../assets/trainers/ei-image284.png'),
  'wally - victory road':    require('../assets/trainers/ei-image284.png'),

  // ── Emerald Imperium — Team Aqua ──────────────────────────────────────────
  'team aqua grunt (petalburg woods)':                              require('../assets/trainers/ei-image143.png'),
  'team aqua grunt - rusturf tunnel (permanent misty terrain)':     require('../assets/trainers/ei-image143.png'),
  'team aqua grunt #1 - slateport museum (back to back)':           require('../assets/trainers/ei-image143.png'),
  'team aqua grunt #2 - slateport museum (back to back)':           require('../assets/trainers/ei-image143.png'),
  'aqua admin matt & grunt (double battle) - weather institute':    require('../assets/trainers/ei-image458.png'),
  'aqua admin matt - seafloor cavern (back to back #2)':            require('../assets/trainers/ei-image458.png'),
  'aqua admin shelly - seafloor cavern (back to back #1)':          require('../assets/trainers/ei-image463.png'),
  'aqua admin shelly - weather institute':                          require('../assets/trainers/ei-image463.png'),
  'aqua leader archie - team aqua hideout':                         require('../assets/trainers/ei-image504.png'),
  'aqua leader archie - seafloor cavern (true double battle)':      require('../assets/trainers/ei-image504.png'),

  // ── Emerald Imperium — Team Magma ─────────────────────────────────────────
  'magma admin courtney & grunt - mt. chimney (double battle)':      require('../assets/trainers/ei-image353.png'),
  'magma admin courtney - magma hideout (back to back #1)':         require('../assets/trainers/ei-image353.png'),
  'magma admin tabitha - mt. chimney':                              require('../assets/trainers/ei-image361.png'),
  'magma admin tabitha - magma hideout (back to back #2)':          require('../assets/trainers/ei-image361.png'),
  'magma leader maxie - mt. chimney':                               require('../assets/trainers/ei-image403.png'),
  'magma leader maxie - magma hideout (true double battle)':        require('../assets/trainers/ei-image403.png'),

  // ── Emerald Imperium — Route Trainers ────────────────────────────────────
  'collector edwin - route 110':                                    require('../assets/trainers/ei-image262.png'),
  'guitarist joseph - route 110':                                   require('../assets/trainers/ei-image263.png'),
  'guitarist brian':                                                require('../assets/trainers/ei-guitarist-brian.png'),
  'guitarist brian (true double battle)':                           require('../assets/trainers/ei-guitarist-brian.png'),
  'psychic edward - route 110':                                     require('../assets/trainers/ei-image265.png'),
  'pokefan isabel & kaleb (double battle) - route 110':             require('../assets/trainers/ei-image237.png'),
  'triathlete alyssa - route 110':                                  require('../assets/trainers/ei-image318.png'),
  'triathlete grace & declan double battle - route 124 (permanent sun)': require('../assets/trainers/ei-image543.png'),
  'battle girl jenny - route 124 (permanent sun)':                  require('../assets/trainers/ei-image544.png'),
  'kindler spencer - route 124 (permanent sun)':                    require('../assets/trainers/ei-image538.png'),
  'winstrate victor - route 111 (back to back #1) (optional)':      require('../assets/trainers/ei-image237.png'),
  'winstrate victoria - route 111 (back to back #2) (optional)':    require('../assets/trainers/ei-image242.png'),
  'winstrate vivi - route 111 (back to back #3) (optional)':        require('../assets/trainers/ei-image399.png'),
  'winstrate vicky - route 111 (back to back #4) (optional)':       require('../assets/trainers/ei-image448.png'),
  'black belt daisuke - route 111 (optional)':                      require('../assets/trainers/ei-image317.png'),
  'camper celia - route 111 (permanent sand)':                      require('../assets/trainers/ei-image355.png'),
  'camper drew & branden - route 111 (permanent sand) (double battle)': require('../assets/trainers/ei-image355.png'),
  'hiker dusty - route 111 (permanent sand)':                       require('../assets/trainers/ei-image328.png'),
  'hiker trent - route 112':                                        require('../assets/trainers/ei-image328.png'),
  'fisherman kai - route 114 (permanent snow)':                     require('../assets/trainers/ei-image315.png'),
  'fisherman claude - route 114 (permanent snow)':                  require('../assets/trainers/ei-image315.png'),
  'hiker lucas - route 114 (permanent snow)':                       require('../assets/trainers/ei-image328.png'),
  'camper charlotte - route 114 (permanent snow)':                  require('../assets/trainers/ei-image355.png'),
  'parasol madeline - route 113':                                    require('../assets/trainers/ei-image330.png'),
  'tori and tia - route 113 (true double battle)':                  require('../assets/trainers/ei-image340.png'),
  'sailor dwayne':                                                   require('../assets/trainers/ei-sailor-dwayne.png'),
  'beauty johanna':                                                  require('../assets/trainers/ei-beauty-johanna.png'),
  'breeder lydia - route 117 (optional)':                           require('../assets/trainers/ei-image277.png'),
  'breeder ezekiel - route 117 (optional)':                         require('../assets/trainers/ei-image309.png'),
  'beauty jessica - route 121 (permanent rain)':                    require('../assets/trainers/ei-image524.png'),
  'gentleman walter & pokefan vanessa - route 121 (permanent rain) (double battle)': require('../assets/trainers/ei-image529.png'),
  'maniac cale - route 121 (permanent rain)':                       require('../assets/trainers/ei-image530.png'),
  'maniac tammy - route 121 (permanent rain)':                      require('../assets/trainers/ei-image530.png'),
  'ursula - verdanturf town (double battle) (optional)':            require('../assets/trainers/ei-image348.png'),

  // ── Emerald Imperium — Trick House ────────────────────────────────────────
  'lass sally - trick house (puzzle 1)':       require('../assets/trainers/ei-image399.png'),
  'lass robin - trick house (puzzle 1)':       require('../assets/trainers/ei-image399.png'),
  'youngster eddie - trick house (puzzle 1)':  require('../assets/trainers/ei-image427.png'),
  'girl georgia - trick house (puzzle 2)':     require('../assets/trainers/ei-image399.png'),
  'kid ted - trick house (puzzle 2)':          require('../assets/trainers/ei-image427.png'),
  'picknicker rachel - trick house (puzzle 2)': require('../assets/trainers/ei-image430.png'),
  'camper rusty - trick house (puzzle 3)':     require('../assets/trainers/ei-image355.png'),
  'picnicker martha- trick house (puzzle 3)':  require('../assets/trainers/ei-image355.png'),
  'hiker alan - trick house (puzzle 3)':       require('../assets/trainers/ei-image328.png'),

  // ── Emerald Imperium — Victory Road & Optional Trainers ──────────────────
  'cooltrainer albert - victory road':   require('../assets/trainers/ei-image607.png'),
  'cooltrainer samuel - victory road':   require('../assets/trainers/ei-image607.png'),
  'cooltrainer felix - victory road':    require('../assets/trainers/ei-image607.png'),
  'cooltrainer hope - victory road':     require('../assets/trainers/ei-image681.png'),
  'cooltrainer caroline - victory road': require('../assets/trainers/ei-image681.png'),
  'cooltrainer michelle - victory road': require('../assets/trainers/ei-image681.png'),
  'trainer iriv24 - fortree city (optional)':                              require('../assets/trainers/ei-image508.png'),
  'trainer x - fortree city (optional)':                                   require('../assets/trainers/ei-image508.png'),
  'trainer cap - fortree city (optional)':                                 require('../assets/trainers/ei-image508.png'),
  'trainer sunbird - mossdeep city (optional - tyrantrum follower)':       require('../assets/trainers/ei-image607.png'),
  'trainer suneal - mossdeep city (optional - kingambit follower)':        require('../assets/trainers/ei-image607.png'),
  'trainer dollamike - mossdeep city (optional - blaziken follower)':      require('../assets/trainers/ei-image607.png'),
  'trainer danni - sootopolis city (optional - urshifu follower)':         require('../assets/trainers/ei-image607.png'),
  'trainer masta janes - sootopolis city (optional - meowscarada follower)': require('../assets/trainers/ei-image607.png'),
  'trainer befools - sootopolis city (optional - gengar follower)':        require('../assets/trainers/ei-image607.png'),
  'trainer natn - sootopolis city (optional - kingambit follower)':        require('../assets/trainers/ei-image607.png'),
  'trainer master poucine - sootopolis city (optional - dragapult follower)': require('../assets/trainers/ei-image607.png'),
  'trainer oblivion wing - sootopolis city (optional greninja follower)':  require('../assets/trainers/ei-image607.png'),
  'trainer burak - sootopolis city (optional - spidops follower)':         require('../assets/trainers/ei-image607.png'),
};

export function resolveTrainerSprite(name: string | null): number | null {
  if (!name) return null;
  const lc = name.toLowerCase();
  if (TRAINER_SPRITE[lc] != null) return TRAINER_SPRITE[lc];
  for (const key of Object.keys(TRAINER_SPRITE)) {
    if (lc.startsWith(key)) return TRAINER_SPRITE[key];
  }
  return null;
}
