// Trainer sprite lookup — exact name first, then trainer-class prefix.
// Keys are lowercase. Prefix keys (e.g. 'youngster') must come AFTER any longer
// exact keys so the prefix check doesn't shadow specific entries.

export const TRAINER_SPRITE: Record<string, number> = {
  // ── Radical Red — Named characters ───────────────────────────────────────
  'ariana':                        require('../assets/trainers/ariana.png'),
  'brendan':                       require('../assets/trainers/brendan.png'),
  'brendan (s.s. anne)':           require('../assets/trainers/brendan-ss.png'),
  'may':                           require('../assets/trainers/may.png'),
  'sam first fight':               require('../assets/trainers/beauty.png'),
  'shelly second fight':           require('../assets/trainers/beauty.png'),
  'rocket admin archer':           require('../assets/trainers/rocket-admin.png'),
  'nugget bridge grunt':           require('../assets/trainers/rocket-grunt.png'),
  'team rocket grunt':             require('../assets/trainers/rocket-grunt.png'),
  'rocket grunt guard':            require('../assets/trainers/rocket-grunt.png'),
  'super nerd miguel':             require('../assets/trainers/super-nerd.png'),
  'cue ball camron':               require('../assets/trainers/biker.png'),
  // Gary — varies by starter choice
  'if you chose bulbasaur':        require('../assets/trainers/gary.png'),
  'if you chose charmander':       require('../assets/trainers/gary.png'),
  'if you chose squirtle':         require('../assets/trainers/gary.png'),
  'if you chose a fire starter':   require('../assets/trainers/gary-alt.png'),
  'if you chose a water starter':  require('../assets/trainers/gary-alt.png'),

  // ── Radical Red — Trainer classes (prefix-matched) ───────────────────────
  'youngster':    require('../assets/trainers/youngster.png'),
  'bug catcher':  require('../assets/trainers/bug-catcher.png'),
  'camper':       require('../assets/trainers/camper.png'),
  'picnicker':    require('../assets/trainers/picnicker.png'),
  'ace trainer':  require('../assets/trainers/ace-trainer-m.png'),
  'rocket grunt': require('../assets/trainers/rocket-grunt.png'),
  'rocket admin': require('../assets/trainers/rocket-admin.png'),
  'dragon tamer': require('../assets/trainers/dragon-tamer.png'),
  'cue ball':     require('../assets/trainers/biker.png'),
  'super nerd':   require('../assets/trainers/super-nerd.png'),
  'sailor':       require('../assets/trainers/sailor.png'),

  // ── Emerald Imperium — Gym Leaders & Elite Four ───────────────────────────
  'roxanne':                                                          require('../assets/trainers/ei-image31.png'),
  'roxanne - rustboro city':                                          require('../assets/trainers/ei-image31.png'),
  'brawly - dewford town':                                            require('../assets/trainers/ei-image6.png'),
  'wattson':                                                          require('../assets/trainers/ei-image67.png'),
  'wattson - mauville city':                                          require('../assets/trainers/ei-image67.png'),
  'flannery':                                                         require('../assets/trainers/ei-image44.png'),
  'norman':                                                           require('../assets/trainers/ei-image53.png'),
  'norman - petalburg city':                                          require('../assets/trainers/ei-image53.png'),
  'winona':                                                           require('../assets/trainers/ei-image15.png'),
  'winona - fortree city':                                            require('../assets/trainers/ei-image15.png'),
  'tate & liza (double battle)':                                      require('../assets/trainers/ei-image35.png'),
  'tate & liza (double battle) - mossdeep city':                     require('../assets/trainers/ei-image35.png'),
  'juan - sootopolis city':                                           require('../assets/trainers/ei-image42.png'),
  'candice - route 116':                                              require('../assets/trainers/ei-image287.png'),
  'gardenia - petalburg woods (pre-3rd gym badge)':                   require('../assets/trainers/ei-image122.png'),
  'gardenia - petalburg woods (post 3rd gym badge)':                  require('../assets/trainers/ei-image122.png'),
  'gardenia - petalburg woods (post 3rd gym badge) (optional)':       require('../assets/trainers/ei-image122.png'),
  'fantina - route 117':                                              require('../assets/trainers/ei-image93.png'),
  'fantina - route 117 (optional)':                                   require('../assets/trainers/ei-image93.png'),
  'maylene - jagged pass':                                            require('../assets/trainers/ei-image110.png'),
  'maylene - jagged pass (optional)':                                 require('../assets/trainers/ei-image110.png'),
  'crasher wake - route 118 (surf required)':                         require('../assets/trainers/ei-image115.png'),
  'crasher wake - route 118 (optional) (surf required)':              require('../assets/trainers/ei-image115.png'),
  'byron - route 121 (permanent rain)':                               require('../assets/trainers/ei-image124.png'),
  'byron - route 121 (permanent rain) (optional)':                    require('../assets/trainers/ei-image124.png'),
  'roark - outside shoal cave':                                       require('../assets/trainers/ei-image128.png'),
  'volkner - evergrande city (optional)':                             require('../assets/trainers/ei-image150.png'),
  'elite four - sidney (team 1) aka sydney tailwind':                 require('../assets/trainers/ei-image708.png'),
  'elite four - sidney (team 2) aka sydney trickroom':                require('../assets/trainers/ei-image708.png'),
  'elite four - phoebe (team 1) aka phoebe dusknoir':                 require('../assets/trainers/ei-image348.png'),
  'elite four - phoebe (team 2) aka phoebe gengar':                   require('../assets/trainers/ei-image348.png'),
  'elite four - glacia (team 1) aka glacia sun':                      require('../assets/trainers/ei-image732.png'),
  'elite four - glacia (team 2) aka glacia snow':                     require('../assets/trainers/ei-image732.png'),
  'elite four drake - sky pillar (true double battle)':               require('../assets/trainers/ei-image604.png'),
  'elite four - cynthia':                                             require('../assets/trainers/ei-image750.png'),

  // ── Emerald Imperium — Rivals ─────────────────────────────────────────────
  'rival fight (brendan / may) - route 103 (chooses type that beats your starter)': require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - rustboro city (if you chose grass starter)':       require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - rustboro city (if you chose fire starter)':        require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - route 110 (if you chose water starter)':           require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 110 (if you chose grass starter)':           require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 110 (if you chose fire starter)':            require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - rustboro city (if you chose water starter)':        require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 119 (if you chose water starter)':           require('../assets/trainers/ei-image133.png'),
  'rival fight (brendan / may) - route 119 (if you chose grass starter)':           require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - route 119 (if you chose fire starter)':            require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - evergrande city (if you chose water starter)':     require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - evergrande city (if you chose grass starter)':     require('../assets/trainers/ei-image134.png'),
  'rival fight (brendan / may) - evergrande city (if you chose fire starter)':      require('../assets/trainers/ei-image134.png'),
  'wally - mauville city':   require('../assets/trainers/ei-image284.png'),
  'wally - route 110':       require('../assets/trainers/ei-image284.png'),
  'wally - victory road':    require('../assets/trainers/ei-image284.png'),

  // ── Emerald Imperium — Team Aqua ──────────────────────────────────────────
  'team aqua grunt (petalburg woods)':                              require('../assets/trainers/ei-image143.png'),
  'team aqua grunt - rusturf tunnel (permanent misty terrain)':     require('../assets/trainers/ei-image143.png'),
  'team aqua grunt #1 - slateport museum (back to back)':           require('../assets/trainers/ei-image143.png'),
  'team aqua grunt #2 - slateport museum (back to back)':           require('../assets/trainers/ei-image143.png'),
  'aqua admin matt & grunt (double battle) - weather institute':    require('../assets/trainers/ei-image458.png'),
  'aqua admin matt - seafloor cavern (back to back #2)':            require('../assets/trainers/ei-image458.png'),
  'aqua admin shelly - seafloor cavern (back to back #1)':          require('../assets/trainers/ei-image463.png'),
  'aqua admin shelly - weather institute':                          require('../assets/trainers/ei-image463.png'),
  'aqua leader archie - team aqua hideout':                         require('../assets/trainers/ei-image504.png'),
  'aqua leader archie - seafloor cavern (true double battle)':      require('../assets/trainers/ei-image504.png'),

  // ── Emerald Imperium — Team Magma ─────────────────────────────────────────
  'magma admin courtney - magma hideout (back to back #1)':         require('../assets/trainers/ei-image353.png'),
  'magma admin tabitha - mt. chimney':                              require('../assets/trainers/ei-image361.png'),
  'magma admin tabitha - magma hideout (back to back #2)':          require('../assets/trainers/ei-image361.png'),
  'magma leader maxie - mt. chimney':                               require('../assets/trainers/ei-image403.png'),
  'magma leader maxie - magma hideout (true double battle)':        require('../assets/trainers/ei-image403.png'),

  // ── Emerald Imperium — Route Trainers ────────────────────────────────────
  'collector edwin - route 110':                                    require('../assets/trainers/ei-image262.png'),
  'guitarist joseph - route 110':                                   require('../assets/trainers/ei-image263.png'),
  'psychic edward - route 110':                                     require('../assets/trainers/ei-image265.png'),
  'pokefan isabel & kaleb (double battle) - route 110':             require('../assets/trainers/ei-image237.png'),
  'triathlete alyssa - route 110':                                  require('../assets/trainers/ei-image318.png'),
  'winstrate victor - route 111 (back to back #1) (optional)':      require('../assets/trainers/ei-image237.png'),
  'winstrate victoria - route 111 (back to back #2) (optional)':    require('../assets/trainers/ei-image242.png'),
  'winstrate vivi - route 111 (back to back #3) (optional)':        require('../assets/trainers/ei-image399.png'),
  'winstrate vicky - route 111 (back to back #4) (optional)':       require('../assets/trainers/ei-image448.png'),
  'black belt daisuke - route 111 (optional)':                      require('../assets/trainers/ei-image317.png'),
  'camper celia - route 111 (permanent sand)':                      require('../assets/trainers/ei-image355.png'),
  'camper drew & branden - route 111 (permanent sand) (double battle)': require('../assets/trainers/ei-image355.png'),
  'hiker dusty - route 111 (permanent sand)':                       require('../assets/trainers/ei-image328.png'),
  'hiker trent - route 112':                                        require('../assets/trainers/ei-image328.png'),
  'fisherman kai - route 114 (permanent snow)':                     require('../assets/trainers/ei-image315.png'),
  'fisherman claude - route 114 (permanent snow)':                  require('../assets/trainers/ei-image315.png'),
  'hiker lucas - route 114 (permanent snow)':                       require('../assets/trainers/ei-image328.png'),
  'camper charlotte - route 114 (permanent snow)':                  require('../assets/trainers/ei-image355.png'),
  'breeder lydia - route 117 (optional)':                           require('../assets/trainers/ei-image277.png'),
  'breeder ezekiel - route 117 (optional)':                         require('../assets/trainers/ei-image309.png'),
  'beauty jessica - route 121 (permanent rain)':                    require('../assets/trainers/ei-image524.png'),
  'gentleman walter & pokefan vanessa - route 121 (permanent rain) (double battle)': require('../assets/trainers/ei-image529.png'),
  'maniac cale - route 121 (permanent rain)':                       require('../assets/trainers/ei-image530.png'),
  'maniac tammy - route 121 (permanent rain)':                      require('../assets/trainers/ei-image530.png'),
  'ursula - verdanturf town (double battle) (optional)':            require('../assets/trainers/ei-image348.png'),

  // ── Emerald Imperium — Trick House ────────────────────────────────────────
  'lass sally - trick house (puzzle 1)':       require('../assets/trainers/ei-image399.png'),
  'lass robin - trick house (puzzle 1)':       require('../assets/trainers/ei-image399.png'),
  'youngster eddie - trick house (puzzle 1)':  require('../assets/trainers/ei-image427.png'),
  'girl georgia - trick house (puzzle 2)':     require('../assets/trainers/ei-image399.png'),
  'kid ted - trick house (puzzle 2)':          require('../assets/trainers/ei-image427.png'),
  'picknicker rachel - trick house (puzzle 2)': require('../assets/trainers/ei-image430.png'),
  'camper rusty - trick house (puzzle 3)':     require('../assets/trainers/ei-image355.png'),
  'picnicker martha- trick house (puzzle 3)':  require('../assets/trainers/ei-image355.png'),
  'hiker alan - trick house (puzzle 3)':       require('../assets/trainers/ei-image328.png'),

  // ── Emerald Imperium — Victory Road & Optional Trainers ──────────────────
  'cooltrainer albert - victory road':   require('../assets/trainers/ei-image607.png'),
  'cooltrainer samuel - victory road':   require('../assets/trainers/ei-image607.png'),
  'cooltrainer felix - victory road':    require('../assets/trainers/ei-image607.png'),
  'cooltrainer hope - victory road':     require('../assets/trainers/ei-image681.png'),
  'cooltrainer caroline - victory road': require('../assets/trainers/ei-image681.png'),
  'cooltrainer michelle - victory road': require('../assets/trainers/ei-image681.png'),
  'trainer iriv24 - fortree city (optional)':                              require('../assets/trainers/ei-image508.png'),
  'trainer x - fortree city (optional)':                                   require('../assets/trainers/ei-image508.png'),
  'trainer cap - fortree city (optional)':                                 require('../assets/trainers/ei-image508.png'),
  'trainer sunbird - mossdeep city (optional - tyrantrum follower)':       require('../assets/trainers/ei-image607.png'),
  'trainer suneal - mossdeep city (optional - kingambit follower)':        require('../assets/trainers/ei-image607.png'),
  'trainer dollamike - mossdeep city (optional - blaziken follower)':      require('../assets/trainers/ei-image607.png'),
  'trainer danni - sootopolis city (optional - urshifu follower)':         require('../assets/trainers/ei-image607.png'),
  'trainer masta janes - sootopolis city (optional - meowscarada follower)': require('../assets/trainers/ei-image607.png'),
  'trainer befools - sootopolis city (optional - gengar follower)':        require('../assets/trainers/ei-image607.png'),
  'trainer natn - sootopolis city (optional - kingambit follower)':        require('../assets/trainers/ei-image607.png'),
  'trainer master poucine - sootopolis city (optional - dragapult follower)': require('../assets/trainers/ei-image607.png'),
  'trainer oblivion wing - sootopolis city (optional greninja follower)':  require('../assets/trainers/ei-image607.png'),
  'trainer burak - sootopolis city (optional - spidops follower)':         require('../assets/trainers/ei-image607.png'),
};

export function resolveTrainerSprite(name: string | null): number | null {
  if (!name) return null;
  const lc = name.toLowerCase();
  if (TRAINER_SPRITE[lc] != null) return TRAINER_SPRITE[lc];
  for (const key of Object.keys(TRAINER_SPRITE)) {
    if (lc.startsWith(key)) return TRAINER_SPRITE[key];
  }
  return null;
}
