#!/usr/bin/env python3
"""Generate lib/spriteMap.ts from sprites in assets/sprites/static/."""

from pathlib import Path

ROOT       = Path(__file__).parent.parent
SPRITE_DIR = ROOT / "assets" / "sprites" / "static"
OUT_FILE   = ROOT / "lib" / "spriteMap.ts"

sprites = sorted(p.stem for p in SPRITE_DIR.glob("*.png"))

lines = [
    "// AUTO-GENERATED by etl/gen_sprite_map.py — do not edit manually",
    "// Re-run: python3 etl/gen_sprite_map.py",
    "",
    "export const SPRITE_MAP: Record<string, number> = {",
]
for stem in sprites:
    lines.append(f'  "{stem}": require("../assets/sprites/static/{stem}.png"),')
lines.append("};")

OUT_FILE.write_text("\n".join(lines) + "\n")
print(f"Generated {OUT_FILE} with {len(sprites)} sprites")
